-- Database and schema setup
CREATE DATABASE po_crud_db;

\connect po_crud_db;

CREATE SCHEMA IF NOT EXISTS procurement;

SET search_path TO procurement;

-- Users master data
CREATE TABLE procurement.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(500) NOT NULL,
    last_name varchar(500) NOT NULL,
    email varchar(255),
    phone varchar(50),
    created_by varchar(100),
    updated_by varchar(100),
    created_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Items master data
CREATE TABLE procurement.items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(500) NOT NULL,
    description varchar(500),
    price integer NOT NULL,
    cost integer NOT NULL,
    created_by varchar(100),
    updated_by varchar(100),
    created_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Purchase order header
CREATE TABLE procurement.po_h (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description varchar(500),
    total_price integer NOT NULL DEFAULT 0,
    total_cost integer NOT NULL DEFAULT 0,
    created_by varchar(100),
    updated_by varchar(100),
    created_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Purchase order detail
CREATE TABLE procurement.po_d (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poh_id integer NOT NULL,
    item_id integer NOT NULL,
    item_qty integer NOT NULL CHECK (item_qty > 0),
    item_cost integer NOT NULL,
    item_price integer NOT NULL,
    created_by varchar(100),
    updated_by varchar(100),
    created_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_po_detail_header
        FOREIGN KEY (poh_id) REFERENCES procurement.po_h(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_detail_item
        FOREIGN KEY (item_id) REFERENCES procurement.items(id)
);

CREATE INDEX idx_po_d_poh_id ON procurement.po_d (poh_id);
CREATE INDEX idx_po_d_item_id ON procurement.po_d (item_id);
