CREATE SCHEMA IF NOT EXISTS procurement;
SET search_path TO procurement;

CREATE TABLE IF NOT EXISTS procurement.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(500) NOT NULL,
    last_name VARCHAR(500) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    created_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS procurement.items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    price INTEGER NOT NULL,
    cost INTEGER NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    created_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS procurement.po_h (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description VARCHAR(500),
    total_price INTEGER NOT NULL DEFAULT 0,
    total_cost INTEGER NOT NULL DEFAULT 0,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    created_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS procurement.po_d (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poh_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    item_qty INTEGER NOT NULL CHECK (item_qty > 0),
    item_cost INTEGER NOT NULL,
    item_price INTEGER NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    created_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_po_detail_header FOREIGN KEY (poh_id) REFERENCES procurement.po_h(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_detail_item FOREIGN KEY (item_id) REFERENCES procurement.items(id)
);

CREATE INDEX IF NOT EXISTS idx_po_d_poh_id ON procurement.po_d (poh_id);
CREATE INDEX IF NOT EXISTS idx_po_d_item_id ON procurement.po_d (item_id);

TRUNCATE TABLE procurement.po_d, procurement.po_h, procurement.items, procurement.users RESTART IDENTITY CASCADE;

INSERT INTO procurement.users (id, first_name, last_name, email, phone, created_by, updated_by)
VALUES
    (1, 'Dewi', 'Santoso', 'dewi.santoso@example.com', '+62-812-0000-1234', 'system', 'system'),
    (2, 'Budi', 'Wijaya', 'budi.wijaya@example.com', '+62-811-5555-9876', 'system', 'system');

INSERT INTO procurement.items (id, name, description, price, cost, created_by, updated_by)
VALUES
    (1, 'Laptop Pro 15', '15-inch laptop for power users', 18000000, 12000000, 'system', 'system'),
    (2, 'Monitor 27 UHD', '27-inch 4K IPS monitor', 4500000, 3000000, 'system', 'system'),
    (3, 'Mechanical Keyboard', 'RGB mechanical keyboard with brown switches', 1500000, 900000, 'system', 'system');

INSERT INTO procurement.po_h (id, po_datetime, description, total_price, total_cost, created_by, updated_by)
VALUES
    (1, CURRENT_TIMESTAMP - INTERVAL '2 days', 'Office equipment purchase', 21000000, 13800000, 'system', 'system'),
    (2, CURRENT_TIMESTAMP - INTERVAL '1 day', 'Home office accessories', 15000000, 9900000, 'system', 'system');

INSERT INTO procurement.po_d (id, poh_id, item_id, item_qty, item_cost, item_price, created_by, updated_by)
VALUES
    (1, 1, 1, 1, 12000000, 18000000, 'system', 'system'),
    (2, 1, 3, 2, 900000, 1500000, 'system', 'system'),
    (3, 2, 2, 3, 3000000, 4500000, 'system', 'system'),
    (4, 2, 3, 1, 900000, 1500000, 'system', 'system');
